wirenboard/wirenboard

wbdev

Overriding is done via environment variable $IMAGE

wbdev: Allow overriding docker image

---

wbdev

Mount workspace into $HOME/wbdev/go/src/github.com/contactless
and set DEV_DIR accrodingly.

Allow wbdev gdeb to be run anywhere

---

rootfs/create_rootfs.sh
rootfs/rootfs_env.sh

Единственное существенное изменение которое может что-то сломать - при прописывании дополнительных репозиториев значение distro по дефолту берется из $RELEASE (wheezy), раньше там был захардкожен testing, для старого поведения надо выставить переменную окружения ADD_REPO_RELEASE=testing.

rootfs minor fixes

---

rootfs/create_rootfs.sh

Install logrotate package at stretch
logrotate config:
https://github.com/contactless/wb-configs/pull/9

install logrotate

---

rootfs/create_rootfs.sh

Signed-off-by: Nikita webconn Maslov <wkernelteam@gmail.com>

rootfs: add wb-dt-overlays package to common packages list

---

wbdev

devenv: fix docker tag

---

devenv/Dockerfile

Also remove (dead) emdebian.org repo

Go version bump to 1.13.1

---

devenv/Dockerfile
devenv/build.sh
devenv/entrypoint.sh

* install nodejs from stretch-backports
* fix chroot apt preferences file
* check unstable suite exists before applying (fix WB5 builds)
Squash and merge is allowed

devenv: prepare for homeui build in sbuild

---

image/create_images.sh

Привёл в порядок процедуру, теперь zImage для создания FIT скачивается с fw-releases.wirenboard.com.
Минимально обновлённая инструкция здесь: https://wirenboard.com/wiki/Сборка_образов_прошивки
Процедуру проверил на чистой Ubuntu 20.04 LTS, контроллер Wiren Board 6.7, обновлял через Web-интерфейс и с USB-флешки.

image: add option to download zImage from fw-releases.wirenboard.com

---

devenv/Dockerfile

Добавил clang-format в devenv, чтобы потом его использовать в дженкинсе для проверки форматирования исходников

clang-format is added to devenv

---

image/create_images.sh
image/create_update.sh

Это чинит сломавшееся обновление с USB после выхода релиза. Это сломалось после перехода на новое ядро, при сборке образа загрузочное ядро берётся из fw-releases (там сейчас 4.x), а dtb - из rootfs (от нового ядра 5.x).
Сделал так, чтобы dtb при сборке загрузочных ядер также загружалось на fw-releases и использовалось при сборке фита.
Обновлю загрузочное ядро позже при подготовке образов для wb7.

image: download DTB from fw-releases

---

boards/include/soc_imx6ul.sh
image/create_images.sh

Исправляет обновление с флешки на WB69

image: add special DTB for FIT images for wb6x

---

image/install_update.sh
initramfs/create_initramfs.sh
initramfs/files/usb_net.sh

* initramfs: add missing tools for the new initenv process
* initramfs: set explicit MAC for g_ether
* image: add install_update.sh flags to support installation on bare Wiren Board

prepare for a new production process

---

ci/pipelines/releaseImages.groovy
devenv/build.sh
devenv/entrypoint.sh
rootfs/create_rootfs.sh

Что сделано:
- добавлены репозитории bullseye
- удалены пакеты, которых в bullseye больше нет (и непонятно, нужны ли они вообще были)
- добавлен schroot с bullseye в devenv

rootfs, devenv: add bullseye support

---

devenv/Dockerfile

- added low-priority testing repo for the sake of modern pylint version
- added black and isort

added dependencies for python checks

---

devenv/entrypoint.sh

Now `wbdev cdeb` should be used to build all packages using sbuild. This allows to build arch-all packages with platform-specific repos (e.g. for WB6, WB7).
`wbdev ndeb` with sbuild is now deprecated, continues with warning.
Docs: https://github.com/wirenboard/codestyle/pull/32

devenv: build both arch-all and arch-any separately

---

ci/pipelines/uploadDeb.groovy

Пайплайн для ручной загрузки deb-файлов в репозиторий

ci: initial commit for uploadDeb

---

devenv/build.sh

react to https://github.com/wirenboard/wirenboard/pull/114#issuecomment-1496583554

devenv: build chroot with stable bullseye image

---

devenv/build.sh

Починил сборку devenv, которая отдельно зависела от репозитория со stretch

devenv: use stretch from archive in chroot

---

rootfs/create_rootfs.sh

В последних билдах от сегодняшнего дня возникает ошибка при импорте ключа через apt-key. Использование gpg вручную решило проблему

rootfs: do not use apt-key to install keyring

---

README.md

заводил wbdev на свежем десктопе - сначала он отказывался сотрудничать

add qemu-user-static package tp readme

---

boards/6-usbgadget.sh
boards/7-usbgadget.sh
initramfs/create_initramfs.sh
initramfs/files/init

Починил сборку образа initramfs на основе bullseye для wb6, а ещё починил скрипт из initramfs, чтобы снова заработало обновление WB6 с флешки в старом режиме

wb6: fix initramfs build for new update schema support

---

ci/pipelines/uploadDeb.groovy

Из пайплайна `uploadDeb` все файлы отправлялись с именем `upload.deb` и не переименовывались как надо в репозитории. Это приводит к тому, что через пайплайн нельзя загрузить два пакета (с одинаковым именем) разных версий. 
Здесь это исправлено.

ci: uploadDeb: rename deb file according to debian rules before uploading

---

boards/7-usbgadget.sh
initramfs/files/init

На WB 7.4 watchdog надо явно сбрасывать, добавил это в код init-скрипта

reset watchdogs (+ add missing sfdisk for wb7)

---

README.md
devenv/Dockerfile
devenv/build.sh
rootfs/create_rootfs.sh

`Unable to connect to deb.debian.org`

Use debian-mirror.wirenboard.com

---

devenv/build.sh

Добавил установку зависимостей от tsng в schroot по умолчанию, чтобы не тратить на это время при сборке пакета

devenv: pre-install test-suite-ng build-depends

---

ci/pipelines/checkStaging.groovy

Должно ускорить первичную проверку тестинга в два раза

ci: checkStaging: run build in parallel

---

devenv/build.sh

devenv: enable chroots again

---

devenv/Dockerfile
devenv/build.sh
devenv/common-deps.sh
rootfs/create_rootfs.sh

* j2cli нет в stretch, а KNOWN_BUILD_DEPS устанавливаются только для bullseye
* apt-transport-https в bullseye уже не нужен

Move j2cli to KNOWN_BUILD_DEPS

---

devenv/entrypoint.sh

After:
`WBDEV_TESTING_SETS=foo wbdev cdeb`
Before:
`wbdev cdeb --extra-repository="deb http://deb.wirenboard.com/all experimental.foo main"`

devenv: pass testing set repo spec to sbuild

---

ci/pipelines/releaseImages.groovy

тесты выполняться не будут, т.к. нет стенда, но образы будут сами выкладываться

ci: releaseImages: publish 8x images by default

---

ci/pipelines/buildImage.groovy

ci: buildImage: additional repos example

---

boards/include/soc_sun50i_h616.sh

* https://github.com/wirenboard/wb-metapackages/pull/35

image: add task-wirenboard-wb8 for wb8

---

devenv/build.sh
devenv/common-deps.sh
devenv/entrypoint.sh

Добавила пакет pytest-cov и передачу PYBUILD_TEST_ARGS в чрут при сборке

Add coverage support

---

ci/pipelines/checkStaging.groovy

после выпуска релиза теперь можно

ci: checkStaging: build images for wb8 also

---

ci/pipelines/checkStaging.groovy

кажется, можно возвращать, сейчас сборка wb8 в staging починилась

Revert "Revert "ci: checkStaging: build images for wb8 also""

---

vscode/cpp/.devcontainer/devenv-setup.sh
vscode/cpp/wb-mqtt-serial/.vscode/tasks.json

* lcov -> gcovr
* libwbmqtt1-4 -> libwbmqtt1-5

vscode: lcov -> gcovr

---

devenv/prep.sh

* arm-linux-gnueabi от armel
* wb-mqtt-knx под x86_64 уже давно не собирается

Cleanup prep.sh

---

devenv/entrypoint.sh

devenv: redirect warning to stderr

---

devenv/Dockerfile
devenv/build.sh

wb-rules, wb-mqtt-confed, frp, telegraf уже собираются с go-1.21.

Upgrade golang-go to 1.21

---

ci/pipelines/uploadDeb.groovy

Возможность загружать сразу несколько пакетов в репу одним архивом.

ci: uploadDeb: support archives

---

ci/pipelines/releaseImages.groovy

Возможность прокинуть тестинг-сет репу в сборку фита.

ci: releaseImages: add ADDITIONAL_REPOS param
