devenv/entrypoint.sh
This is useful for at least 4 of our packages and extremely useful for our third-party packages. But we increase build time a bit.
=> Install deps before build

wbdev
Домашние папки на macOS находятся в /Users, а не в /home, из-за этого происходила ошибка при запуске, например, `wbdev chroot`:
```
wbdev chroot
Warning: WBDEV_TARGET is not set, defaulting to armel
proot warning: can't chdir("/Users/virus/wbdev/go/src/github.com/contactless/wb-mqtt-serial/./.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
bash: cd: /Users/virus/wbdev/go/src/github.com/contactless/wb-mqtt-serial: No such file or directory
```
После этого коммита для macOS в контейнере домашняя директория будет браться не из стандартного `$HOME`, а генерироваться на основе имени пользователя.
Работоспособность на macOS проверил запуском `wbdev chroot` и `wbdev make` на wb-mqtt-serial. Под линуксом — не проверял.
=> wbdev: add docker4mac support

rootfs/create_rootfs.sh
Я так понимаю, лучше перед этим PR сначала вмержить PR в wb-configs, чтобы не было сборок, в которых вообще не прописаны репозитории.
С этим PR и исправленным wb-configs будет так:
```
root@wirenboard-AQZBLNTY:~# dpkg -s wb-configs | grep Version
Version: 1.82.1
root@wirenboard-AQZBLNTY:~# ls /etc/apt
apt.conf.d  preferences.d  sources.list.d  trusted.gpg	trusted.gpg.d
root@wirenboard-AQZBLNTY:~# cat /etc/apt/sources.list.d/debian-upstream.list 
deb http://deb.debian.org/debian/ stretch main
deb http://deb.debian.org/debian/ stretch-updates main
deb http://security.debian.org stretch/updates main
root@wirenboard-AQZBLNTY:~# apt update
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease                           
Hit:3 …
```
=> Move standard Debian Stretch repos to wb-configs

README.md, devenv/Dockerfile, devenv/Makefile, devenv/entrypoint.sh, devenv/wbdev_second_half.sh, wbdev
внешний скрипт wbdev получается связан с версией контейнера, что неудобно. Запихнул wbdev внутрь контейнера, снаружи оставил только его вытаскивание из контейнера.
Кроме этого настоящий wbdev (который внутри контейнера) теперь только формирует параметры для докера и не пытается их обрабатывать. В entrypoint передаются как есть все переменные, начинающиеся на WBDEV_. Вся логика теперь в одном месте - внутри entrypoint.
wbdev script is now only extracts and executes actual runner
script from the container.
It's not supposed to be updated.
=> devenv: distribute runner script within container

boards/67.sh
WB6.7 нужен отдельный tag для сборки прошивки. Wb-configs и hwconf смотрят в /proc/device-tree/compatible при установке
=> new board: wb6.7

devenv/build.sh
При генерации rootfs для sbuild заменяем /dev/ptmx на симлинк на /dev/pts/ptmx. Это решает проблему с ошибкой при вызове grantpt в тесте wb-mqtt-serial.
=> /dev/ptmx is replaced by symlink to /dev/pts/ptmx

image/create_images.sh
Если не установить MAKE_IMG - то образ по умолчанию не собирается.
=> Exclude build IMG file by default

devenv/build.sh
We provide our own versions of libcomerr2 and e2fslibs for armel and armhf, but not for amd64. So we can't use them in multiarch mode during crosscompilation with amd64 system. CMake is dependend of these libraries. In order to support CMake distr supplied libraries are installed in devenv.
=> CMake support

devenv/Dockerfile
В перспективе нужно будет складывать всё, что нам нужно в фиксированных версиях, в свой репозиторий, и тянуть оттуда нормальным способом через apt-get. Пока оставим так, чтобы devenv начал собираться.
=> 32964 qemu download source quickfix

devenv/Dockerfile, devenv/build.sh, devenv/entrypoint.sh
Переключил sbuild на новый репозиторий.
stable подключается по умолчанию в зависимости от того, под какой контроллер собираем. unstable можно подключить в дополнение к stable с пониженным приоритетом, установив переменную WBDEV_USE_UNSTABLE_DEPS.
Можно также собрать только с конкретным релизом, прописав его в WB_TARGET_REPO_RELEASE.
=> devenv: use new repository

initramfs/create_initramfs.sh, initramfs/files/init, initramfs/files/libupdate.sh, initramfs/files/wait_for_button.sh
we no longer ask for confirmation for auto-discovered update
.fit files on USB and microSD media.
We also indicate that valid .fit file is discovered by two short beeps
to give a feedback to user without debug console attached.
=> initramfs: wb: do not ask for confirmation before regular update

ci/pipelines/releaseImages.groovy
Загружать IMG после внедрения нового стенда инициализации в целом больше не обязательно, там используются FIT по умолчанию
=> ci: releaseImages: do not upload firmware IMGs by default

devenv/Dockerfile, devenv/build.sh, devenv/entrypoint.sh
Добавил в bullseye репозиторий bullseye-backports (нужен для networkmanager / modemmanager и их зависимостей). Также немного починил логику конфигурирования sbuild через переменные, чтобы можно было задавать релиз и префикс нашего репозитория в умолчаниях.
**UPD 28.07.2022**: clang-format теперь устанавливается из репозитория WB dev-tools, куда был заботливо отправлен после небольшого косметического изменения в строку версии (`~exp` заменил на `~llvmexp`, чтобы не раздражать скрипты wbci этим)
=> devenv: prepare for buillseye-backports

ci/pipelines/publishImage.groovy, image/create_images.sh
В имена FIT-образов теперь включена версия релиза (если собирается образ из stable), а также релиз debian (stretch или bullseye). Последняя версия теперь называется latest.fit по умолчанию (чтобы latest_stretch.fit не получился с bullseye). `latest_stretch.fit` всё ещё можно будет опубликовать вручную.
Также больше не публикуется `latest_stretch_FACTORYRESET.fit`, всё равно смысла в нём не было.
=> New image names format

ci/pipelines/checkStaging.groovy, rootfs/create_rootfs.sh, rootfs/rootfs_env.sh
С переходом на bullseye пайплайн check-staging оказался сломанным, потому что пытался заставить build-image собирать неправильный образ. Этот патч исправляет ошибки.
Также здесь отключается параллельная сборка образов, чтобы не занимать чрезмерно очередь сборки в jenkins.
=> Fix check-staging pipeline for bullseye

ci/pipelines/checkStaging.groovy
Эта опция оказалась сломанной, хотя по факту пригодилась
=> ci: make checkStaging pass WBDEV_IMAGE to buildImage

devenv/Dockerfile
```
#5 29.07 The following packages have unmet dependencies:
#5 29.22  libnode72 : Conflicts: nodejs-legacy
#5 29.22  nodejs : Conflicts: npm
#5 29.26 W: --force-yes is deprecated, use one of the options starting with --allow instead.
#5 29.26 E: Unable to correct problems, you have held broken packages.
```
Проверил билд homeui с новым контейнером.
=> Fix devenv image build

image/install_update.sh
Нужно для того, чтобы postinst-скрипты знали, из какого файла делалось обновление (например, чтобы сохранить файл в .wb-restore при factoryreset)
=> image: pass FIT path to postinst scripts via env

devenv/entrypoint.sh, devenv/wbdev_second_half.sh, wbdev
Попробовал использовать wbdev в связке с контейнером с jenkins agent (на базе Alpine), столкнулся с небольшими проблемами:
- некоторые команды испортились, потому что alpine под капотом имеет busybox с ограниченным числом флагов;
- испортился bind mount при запуске wbdev, поскольку при запуске из контейнера путь в `-v` всё равно надо писать как из хостовой системы.
Для второго я добавил переменную окружения `DEV_VOLUME`, в которую надо передать пару `volume:/path/to/bind`. Этот volume подключится к wbdev вместо обычных `HOME` и `PWD` (естественно, нужно находиться в этот момент в директории, дочерней к `/path/to/mount`).
Заодно убрал `chown` Go-шных библиотек из `entrypoint.sh`, всё равно никому он сейчас не нужен, а времени при запуске отъедает очень много даже с nvme.
=> devenv: make it work when called from Docker container

image/install_update.sh
Если попытаться обновить запрещенным (bullseye -> stretch) fit-ом контроллер несколько раз подряд, то начиная со второго раза, install_update падает при попытке очистки mountpoint'a, жалуясь на то, что device is busy.
Решение - отмонтируем rootfs
=> umount rootfs on failure from webui

ci/pipelines/buildImage.groovy, ci/pipelines/checkStaging.groovy, ci/pipelines/publishImage.groovy, ci/pipelines/releaseImages.groovy
Я добавил тэг `rootfs-builder` к старой сборочной ноде и хочу, чтобы эти пайплайны пока что собирались только там (через alpine сходу не взлетело).
Для сборки rootfs недостаточно одного devenv, она ещё хочет модуль ядра binfmt_misc для запуска qemu (и пытается добавить его руками, почему-то на старой сборочной машине это работает из докера).
Когда починим сборку на alpine, просто добавим тэг `rootfs-builder` к новому сборщику и PR не понадобится.
Этот PR позволяет сейчас использовать новый сборщик для всех остальных пайплайнов.
=> ci: use rootfs-builder tagged node to build rootfs-related pipelines

devenv/Dockerfile
Нужно для того, чтобы собирать этап Github release на всех билдерах одинаково
=> devenv: add python3-wbci to wbdev

devenv/wbdev_second_half.sh
В новом билдере aptly не объявляются переменные USER и UID по умолчанию, этот патч их доопределяет при необходимости
=> devenv: define USER and UID if not defined (required by aptly builder)

initramfs/files/init
Обновление через Web UI без A/B схемы будет делаться примерно так же, как сейчас делается factory reset на WB7 с сохранённого образа. Через u-boot будет задаваться переменная bootmode с путём до FIT-файла.
=> initramfs: add webupdate mode in init

ci/pipelines/buildImage.groovy, ci/pipelines/checkStaging.groovy
* wbci make-ref call compatible with 2.0
* disable concurrent builds
* remove unused wirenboard checkout
Этот пайплайн используется для проверки содержимого staging после пуша в master любого пакета. Он проверяет, что образы прошивок собираются для staging, и в случае успеха передвигают на него снапшот-указатель `unstable.latest`, который можно использовать в releases.yaml для `testing`
=> checkStaging: use new aptly-builder node

devenv/entrypoint.sh
Писал гайдлайн про смену релиза debian (https://github.com/wirenboard/codestyle/pull/21), заодно вспомнил, что у нас мы это не поправили
=> devenv: set bullseye as current release

image/create_update.sh
Вслед за использованием `install_update.sh` из `rootfs`, чтобы получить версионирование скриптов в зависимости от релиза, захотелось брать оттуда же `zImage` и `dtb` для бутлета. В перспективе это позволит брать эти файлы из пакета (и собирать бутлет на CI, прямо как весь остальной софт), сейчас же нужно, чтобы гарантированно установить новый бутлет в сборках с поддержкой `single-rootfs` (будет правка в wb-utils)
=> image: try to use bootlet and DTB from rootfs as well

devenv/Dockerfile
Сейчас в publishImages используется s3 с хоста, что не совсем правильно, лучше из docker
=> devenv: add s3cmd for Jenkins deployments

devenv/entrypoint.sh
Do not override WBDEV_TARGET_REPO_RELEASE if bullseye-armhf or current-armhf WBDEV_TARGET is set
=> Keep WBDEV_TARGET_REPO_RELEASE

devenv/Dockerfile
Эти утилиты нужны, чтобы собирать архив с initramfs для ядра, и чтобы получить в итоге пакет без сложной deb-машинерии (так правда было быстрее).
Ссылка на этот PR останется в коде в wb-initramfs, чтобы удалить оттуда ненужный кусочек потом
=> devenv: add fpm and cpio to build initramfs and bootlets

rootfs/create_rootfs.sh
github перестал отдавать файлы нашим билдсерверам через https, качаем снова с keyserver-а ubuntu (но на этот раз не через apt-key)
=> Bugfix/dont get contactless key from GitHub

devenv/Dockerfile
По аналогии с #164. С первого раза не заработало с keyserver.ubuntu.com, я в итоге просто выложил ключ на S3 (у нас там сейчас работает https, так что безопасно)
=> devenv: install keyring from S3 instead of github

devenv/Dockerfile, devenv/build.sh, devenv/common-deps.sh
Продолжение #168, оказалось недостаточно установить только в sbuild
=> devenv: install known build deps both in docker and schroot

rootfs/rootfs_env.sh
Проблема всплыла после того, как мы отключили внутренний dns в локалке. Проверил в проблемных кэшах, работает
=> rootfs: cleanup old resolv.conf in cached dirs

devenv/build.sh, devenv/entrypoint.sh
Попробовал собрать libwbmqtt1-4, получилось. Остальные пакеты могут потребовать зависимости от libwbmqtt1-4, так что сначала надо будет сделать репозиторий (это следующим PR).
Поскольку репозитория в deb.wirenboard.com для arm64 ещё нет, сделал так, чтобы его наличие было не обязательным (это не должно повлиять на сборки позже, т.к. пакеты не соберутся из-за отсутствия зависимостей)
=> devenv: add arm64 architecture

devenv/Dockerfile, devenv/build.sh, devenv/entrypoint.sh, devenv/schroot/ccache-setup, devenv/schroot/copyfiles, devenv/schroot/fstab, devenv/wbdev_second_half.sh
External Docker volume is forwarded via DEV_CCACHE_VOLUME env variable in wbdev launcher.
Позволяет ускорить сборку пакетов где-то на 20-25% (на примере wb-mqtt-serial и linux).
=> devenv: enable ccache in schroot

wbdev
Не во всех linux дистрибутивах bash живет в `/bin`. А у пользователя желающего собрать [кастомный FIT](https://github.com/wirenboard/custom-fit-image-template) может быть какой угодно дистрибутив.
=> wbdev: fix shebang

devenv/wbdev_second_half.sh
В продолжение https://github.com/wirenboard/wirenboard/pull/177, wbdev_second_half.sh тоже на хосте запускается, не в контейнере.
=> wbdev_second_half.sh: fix shebang

devenv/Dockerfile, devenv/build.sh, devenv/entrypoint.sh
Usage example:
`wbdev compiledb ./clang-tidy-subdirs.sh src test`
=> devenv: generate compile_commands.json

ci/pipelines/publishImage.groovy
Сейчас все загруженные в S3 образы остаются в workspace этой джобы. надо подчищать, тогда не будет неконтролируемо расти потребление места
=> publishImage: clean up after build

devenv/Makefile, devenv/updock.sh, devenv/wbdev_second_half.sh, wbdev
Позволяет использовать `DOCKER=podman wbdev ...` без симлинка docker -> podman (у podman совместимый cli).
=> Use DOCKER variable

devenv/build.sh, devenv/prep.sh
* build.sh: для сборки wb8 рутфс использовать testing релиз
* prep.sh: для linux-headers-wb8 надо добавлять репу с тестинг сетом, но в целом хидеры тут не особо нужно предустанавливать
=> Fix wb8 rootfs build

devenv/build.sh
При добавлении нашей версии ext2fsprogs для arm64 выяснилось, что libext2fs2 (e2fslibs раньше) не может быть установлен вместе с другой версией от другой архитектуры.
Более того, libext2fs-dev (e2fslibs-dev раньше) может быть установлен одновременно только для одной архитектуры, так что нет никакого смысла устанавливать этот пакет заранее.
Этот патч вылечит сборку пакетов для arm64.
=> devenv: use e2fslibs from dev-tools repo

ci/pipelines/uploadDeb.groovy
Починил uploadDeb, чтобы он корректно использовал новую версию wbDeploy
=> ci: uploadDeb: support newer wbDeploy

devenv/build.sh
с предыдущей попытки наладить сборку для arm64 (#189) сломалась сборка libwbmqtt1, там больше прямых зависимостей от e2fsprogs. если решать их так же, как в #189, придётся пересобирать e2fsprogs для wb5, чего мне делать не хочется. в библиотеках существенных изменений нет и можно использовать при сборке пакеты из апстрима, так что так и поступим.
проверил на сборке libwbmqtt1 и wb-mqtt-serial
=> devenv: do not use e2fsprogs from wb repo in devenv to keep host system in order

boards/include/soc_imx23.sh, boards/include/soc_imx28.sh, boards/include/soc_imx6ul.sh, boards/include/soc_sun50i_h616.sh, boards/include/soc_sun8i_r40.sh, image/create_image.sh, image/create_images.sh, image/create_update.sh
Что сделано:
- выкинута сборка .img для WB8, они там совсем не будут использоваться, прошивка на производстве ставится через fit
- автоматически ищется `Image.gz` в папке с бутлетом
- compatible-строка берётся из dtb из бутлета вместо скачанного с S3 (для wb8 не будем выкладывать, это и раньше был костыль)
=> image: Wiren Board 8 images support

ci/pipelines/publishImage.groovy
.img образы прошивки давно не используются, а для WB8 даже не будут собираться, так что отключаю публикацию по умолчанию тут
=> ci: publishImage: set PUBLISH_IMG to false by default

ci/pipelines/checkStaging.groovy
Revert https://github.com/wirenboard/wirenboard/pull/198, стейджинг не собирается без wb8 тестинг сета.
=> Revert "ci: checkStaging: add wb8 (#198)"

ci/pipelines/releaseImages.groovy
Для возможности тестового запуска без реальной публикации фита.
=> ci: releaseImages: add option to disable publishing

ci/pipelines/checkStaging.groovy
Reverts wirenboard/wirenboard#207
там сломана сборка из staging, как выяснилось. пока отключим, чтобы testing шагал, дальше разберёмся
=> Revert "ci: checkStaging: build images for wb8 also"

rootfs/create_rootfs.sh
на CI изначально не работала сборка staging для wb7 и wb8 одновременно, потому что в имени файла с кэшем rootfs никак не была задействована целевая архитектура, из-за чего в прогретом кэше rootfs лежал только один архив со случайной архитектурой (armhf или arm64). соответственно из-за этого одна из целевых версий не собиралась, потому что не могла найти нужные пакеты.
после этого патча должно заработать.
=> rootfs: mix arch into repo_hash to fix rootfs cache for all/staging

devenv/entrypoint.sh
build создавался от рута и у jenkins юзера не было прав на запись
=> devenv: fix compiledb

devenv/entrypoint.sh
Еще фикс, чтобы cmake через pkg-config мог находить зависимости установленные в rootfs.
=> devenv: fix PKG_CONFIG_PATH for compiledb

ci/pipelines/releaseImages.groovy
Для release-images пайплайна в алерте хочется видеть подробности: как минимум с какими BOARDS и WB_RELEASE параметрами был запущен пайплайн.
Depends on https://github.com/wirenboard/jenkins-pipeline-lib/pull/98
=> ci: releaseImages: add details to tg alert

ci/pipelines/releaseImages.groovy
Так как порядок стейджев может быть разный, сходу не очевидно "Test N" это какой борде соответствует:
Например тут 7916 это wb8, 7919 это wb7.
=> ci: releaseImages: fix test stage names

devenv/entrypoint.sh, devenv/prep.sh, devenv/wbdev_second_half.sh
* WBDEV_CCACHE_DIR не передавалось в контейнер, из-за этого вольюм с ccache кешом не использовался
* добавил ccache с конфигом также для chroot
=> devenv: add ccache to chroot

image/create_update.sh
@lostpoint-ru перенес сборку фитов на новую билдноду, и WB стали прошиваться на 30с медленнее. Раскопали - виноват порядок файлов в рутфс (когда dts-ки в начале рутфс - прошивается быстро; когда в конце - медленно)
пот в прошивке есть кусочек, распаковывающий рутфс и проверяющий наличие нужной dts
закрепил порядок
я погонял-попрошивал WB - поломок не заметил
=> sort rootfs files before tgz packing to speedup fit installing

devenv/entrypoint.sh
Before:
```sh
Setting up mosquitto (2.0.20-1-wb101) ...
Installing new version of config file /etc/init.d/mosquitto ...
Installing new version of config file /etc/logrotate.d/mosquitto ...
Configuration file '/etc/mosquitto/mosquitto.conf'
==> Modified (by you or by a script) since installation.
==> Package distributor has shipped an updated version.
What would you like to do about it ?  Your options are:
Y or I  : install the package maintainer's version
N or O  : keep your currently-installed version
D     : show the differences between the versions
Z     : start a shell to examine the situation
The default action is to keep your current version.
*** mosquitto.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package mosquitto (--configure):
end of file on stdin at conffile prompt …
```
=> devenv: ensure non-interactive behavior while choosing the default action

rootfs/create_rootfs.sh
однажды почему-то перестали собираться все FIT-ы. Симптомы - не собирается рутфс на этапе наливания наших пакетов; см картинку
возможно, как-то связано с недавними интернет-делами
вижу, что дженкинс советует установить ca-certificates. Погуглил интернетовы - оказалось, дженкинс дело говорит. Установка ca-certificates в рутфс перед прописыванием наших репозиториев помогла. Как оно работало раньше - тайна, покрытая мраком...
на fw-releases появятся fit-ы за апрель
прописал эту веточку в сборку fit-а; [вот](https://jenkins.wirenboard.com/job/pipelines/job/build-image/10041/parameters/) …
=> reinstall ca-certificates before add repo

ci/pipelines/publishImage.groovy
Проверяем из device-tree что написано в release-suite. Как то раз это место сломали и пользователи не могли обновляться
=> Check release-suite ftom fit file

devenv/wbdev_second_half.sh
```sh
$ wbdev cdeb
...
< no dh_auto_test >
...
```
```sh
$ DEB_BUILD_OPTIONS= wbdev cdeb
...
dh_auto_test -a -O--parallel
make -j8 test
...
```
```sh
$ wbdev cdeb
...
dh_auto_test -a -O--parallel
make -j8 test
...
```
```sh
$ FOO=; docker run -it -e FOO bash bash -c 'test -v FOO && echo defined || echo not-defined'
not-defined
$ export FOO=; docker run -it -e FOO bash bash -c 'test -v FOO && echo defined || echo not-defined'
defined
```
If DEB_BUILD_OPTIONS is not set, `nocheck` is enabled by default.
=> devenv: set DEB_BUILD_OPTIONS

ci/pipelines/publishImage.groovy
недавно @ekateluv внедряла проверочку, что релиз в фите - вида stable/testing, а не wb-2501 (чтобы пользователи потом без проблем обновлялись). Я заметил, что что-то не работает => пусть сама @ekateluv чинит, как вернется
ничего; для нас - fit-ы станут выкладываться на fw-releases
собрал FIT, подхакав то же самое через replay в женкинсе - собралось
=> temporarily disable fixed-release-check

ci/pipelines/publishImage.groovy
Сломалась проверка имени релиза, потому что на тестовом пайплайне варнинг не попадал в вывод команды и на ревью ошибку не заметили. А на проде попадает. Почему так произошло за пару часов разобраться не получилось, подоткнула тейлом
Заработает проверка
Проверила локально что в вывода больше нет варнинга и собрала на тестовом пайплайне
до
```
ekateluv@ekateluv:~/Загрузки$ wbdev user fdtget -d ''  -t s 202504280800_wb-2501_bullseye_wb8x.fit / release-suite
Warning: sbuild+multiarch will be used. Set WBDEV_BUILD_METHOD=qemuchroot for legacy virtualized build.
stable
```
после
``` …
```
=> Fix release name check

rootfs/create_rootfs.sh
* ходить за debian-security через наше зеркало
* task-wb-base-system/task-wb-common-pkgs уже давно есть в релизах, не нужно дублировать
=> devenv: cleanup

devenv/entrypoint.sh
z2m для сборки использует `wbdev chroot ...`, сейчас понадобилось собрать с nodejs 22, которая есть только тестинге пока. Но WBDEV_USE_UNSTABLE_DEPS не работал для chroot.
Возможность использовать тестинг с `wbdev chroot`.
```sh
$ WBDEV_USE_UNSTABLE_DEPS=y ./wbdev chroot bash -c "cat /etc/apt/sources.list.d/wirenboard.list"
Warning: sbuild+multiarch will be used. Set WBDEV_BUILD_METHOD=qemuchroot for legacy virtualized build.
Build target: bullseye-armhf (board wb6)
You can change it by setting WBDEV_TARGET variable (e.g. 'bullseye-armhf'/'bullseye-arm64')
Checking …
```
=> devenv: use WBDEV_USE_UNSTABLE_DEPS for chroot

devenv/build.sh, rootfs/create_rootfs.sh
На контроллер попадают бинарники qemu, хотя они нужны только в devenv:
```
/usr/bin/qemu-aarch64-static: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=c71526bc9963023bb98aececeab81ffe91f16b47, for GNU/Linux 3.2.0, stripped
/usr/bin/qemu-arm-static:     ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=40c96c12d52900a22d8dcd15c383764a70514fba, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root  10M May 13 16:59 /usr/bin/qemu-aarch64-static*
-rwxr-xr-x 1 root root 8.7M May 13 16:59 /usr/bin/qemu-arm-static*
```
Немного уменьшился размер фита. …
=> rootfs: add WB_COPY_QEMU flag

devenv/entrypoint.sh
`platform_has_suite` считает что если ответ [200;400) то сьют есть, а 404 сьюта нет.
Но например в случае редиректа на https:
```sh
curl -sI --output /dev/null --write-out '%{http_code}\n' http://deb.wirenboard.com/wb6/trixie/dists/stable/Release
301
```
Но сьюта не существует:
```sh
curl -sLI --output /dev/null --write-out '%{http_code}\n' http://deb.wirenboard.com/wb6/trixie/dists/stable/Release
404
```
Неверный ответ platform_has_suite далее приводит в добавлению в apt-сорслист несуществующей репы, на чем позднее споткнется apt update.
ничего
на сборке devenv
=> devenv: fix platform_has_suite

devenv/Dockerfile, devenv/build.sh
Все билды в дженкинсе сломались после удаления bullseye-backports:
```sh
+------------------------------------------------------------------------------+
| Update chroot                                                                |
+------------------------------------------------------------------------------+
Hit:2 https://debian-mirror.wirenboard.com/debian bullseye InRelease
Ign:3 https://debian-mirror.wirenboard.com/debian bullseye-backports InRelease
Err:4 https://debian-mirror.wirenboard.com/debian bullseye-backports Release
404  Not Found [IP: 45.89.25.184 443]
Get:1 https://deb.wirenboard.com/dev-tools stable InRelease [13.6 kB]
Get:5 https://deb.wirenboard.com/dev-tools stable/main amd64 Packages …
```
=> Remove bullseye-backports apt source

CODEOWNERS, devenv/entrypoint.sh
Попали в редкую ситуацию, когда dev зависимости для сборки MM в тестинге есть, а в wb-2504 нет (завезли сразу в wb-2507). Казалось бы выставлено `WBDEV_USE_UNSTABLE_DEPS=y`, но как выяснилось оно поддержано только для cdeb+sbuild, но не для cdeb+qemuchroot, а MM как раз тот редкий случай собирается через cdeb+qemuchroot.
ничего
пересобрал devenv, собрал с ним MM.
=> devenv: add WBDEV_USE_UNSTABLE_DEPS support for cdeb+qemuchroot

vscode/cpp/.devcontainer/devenv-setup.sh
Для каждого C++ проекта приходится править скрипт сборки devcontainer, чтобы установить нужные зависимости.
Теперь скрипт сам устанавливает зависимости, получая список из секции `Build-Depends` файла `debian/control`.
Пересобрал devcontainer для `wb-mqtt-serial` с использованием нового скрипта и проверил что нужные зависимости установились.
=> devcontainer: add automatic build depends install feature

devenv/Dockerfile
Сейчас в devenv подключены apt.llvm.org и [dev-tools](https://deb.wirenboard.com/list.html?prefix=dev-tools/pool/main/l/) репы и clang-format-15 пакет есть в обоих, видимо когда-то давно пытались зафиксировать версию, запушив его и в dev-tools, при этом clang-tidy нет в dev-tools.
Что по факту ставится:
```sh
root@wbdevenv:~# apt policy clang-format
clang-format:
Installed: 1:15.0-55~20220203224610.5
Candidate: 1:15.0-55~20220203224610.5
Version table:
*** 1:15.0-55~20220203224610.5 500
500 http://deb.wirenboard.com/dev-tools stable/main amd64 Packages
100 /var/lib/dpkg/status
1:11.0-51+nmu5 500
500 http://deb.debian.org/debian bullseye/main amd64 Packages
root@wbdevenv:~# apt policy clang-format-15 …
```
=> Install clang-format-15/clang-tidy-15 explicitly

rootfs/create_rootfs.sh
При сборке рутфс периодически возникали проблемы с debian-mirror.wirenboard.com зеркалом и приходилось использовать другое. Так можно будет просто передать его в DEBIAN_MIRROR переменной, не трогая сам скрипт.
ничего
=> create-rootfs: add DEBIAN_MIRROR
